### ISSUE TITLE
useNativeDriver was not specified

### ISSUE THREAD

**Issue by NickLewry** [VincentCATILLON/react-native-confetti-cannon#20]
Hi there,

I've just installed and used this and I get the following warning whenever the react-native-confetti-cannon component mounts.

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

"react": "16.11.0",
"react-native": "0.62.2"

Any ideas?

**Comment by VincentCATILLON** [comment]
Hi @NickLewry , thanks for your interest !

Indeed, we are already thinking of using native rendering (GPU) instead of CPU. You can follow the thread [here](https://github.com/VincentCATILLON/react-native-confetti-cannon/issues/18) :) 

I already started a rework to use this setting (which is the default value in future react-native releases) and be able to increase the number of particles rendered at the same time.

First attempts are really promising, so feel free to use it until the GPU rendering is merged :)

**Comment by VincentCATILLON** [comment]
@NickLewry 

Can you try out the 1.2.0 release ? https://www.npmjs.com/package/react-native-confetti-cannon

You should not have your warning anymore 👍

**Comment by NickLewry** [comment]
@VincentCATILLON apologies for the really late reply! yep thats all good thank you!

**Comment by VincentCATILLON** [comment]
Don't worry :) glad to know that the warning has been removed so ;)
